
services:
  redis:
    container_name: redis
    image: redis
    restart: always

    ports: 
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
  backend:
    build: .
    container_name: backend
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn core.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media

    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=tes
      - DEBUG=False
    depends_on:
      - redis
      
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports: 
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - redis
      - backend

volumes:
  static_volume:
  media_volume: